---
- hosts: all
  become: true
  tasks:
    - name: Updating and upgrading the operating system
      apt:
        name: "*"
        state: latest
        update_cache: true
      
- name: Setting up Certificate Authority in Control Node
  hosts: controlNode
  become: yes
  vars:
    ca_cert_path: "/etc/ssl/certs/ca.crt"
    ca_key_path: "/etc/ssl/private/ca.key"
    openssl_config_file: "/etc/ssl/openssl.cnf"
    ca_days: 3650
  tasks:
    - name: Installation of OpenSSL
      package:
        name: openssl
        state: present

    - name: Generating CA Private Key
      openssl_privatekey:
        path: "{{ ca_key_path }}"
        size: 4096
      register: ca_key

    - name: Generating CA Certificate
      openssl_csr:
        path: /etc/ssl/certs/ca.csr
        privatekey_path: "{{ ca_key_path }}"
        common_name: "Certificate Authority"
        country_name: "PH"
        state_or_province_name: "Quezon City"
        locality_name: "TIP"
        organization_name: "Computer Engineering"
        email_address: "qmjaejercito@tip.edu.ph"
      register: ca_csr

    - name: Self Signed CA Certificate
      openssl_certificate:
        path: "{{ ca_cert_path }}"
        privatekey_path: "{{ ca_key_path }}"
        csr_path: /etc/ssl/certs/ca.csr
        provider: selfsigned
        force: true

  handlers:
    - name: Restart OpenSSL Service
      service:
        name: openssl
        state: restarted


- hosts: localhost
  become: yes
  tasks:
    - name: Copy Certificate from Control Node to Manage Node
      copy:
        src: /etc/ssl/certs/ca-certificates.crt
        dest: /home/mj/CPE243_9/certificate

